import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "../../../auth";
import { prisma } from "@/lib/prisma";
import Operations from "./operations";
import OrderStatus from "./order-status";
import ProductForm from "./product-form";
import ProductStatus from "./product-status";
import ProductEditor from "./product-editor";
import VariantEditor from "./variant-editor";
import VariantForm from "./variant-form";

const money = (value: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(value);

export default async function AdminPage() {
  const session = await auth();
  if (session?.user.role !== "ADMIN") redirect("/login");

  const [products, orders, pendingOrders, lowStockVariants, inventory, movements, sales, purchases] = await Promise.all([
    prisma.product.count(),
    prisma.order.findMany({ include: { user: { select: { name: true, email: true, phone: true } }, items: true }, orderBy: { createdAt: "desc" }, take: 12 }),
    prisma.order.count({ where: { status: "PENDING" } }),
    prisma.productVariant.count({ where: { stock: { lte: 2 } } }),
    prisma.product.findMany({ include: { variants: true }, orderBy: { name: "asc" } }),
    prisma.stockMovement.findMany({ include: { variant: { include: { product: { select: { name: true } } } } }, orderBy: { createdAt: "desc" }, take: 20 }),
    prisma.posSale.findMany({ include: { items: true }, orderBy: { createdAt: "desc" }, take: 20 }),
    prisma.purchase.findMany({ include: { items: true }, orderBy: { createdAt: "desc" }, take: 20 }),
  ]);
  const startOfToday = new Date();
  startOfToday.setHours(0, 0, 0, 0);
  const todaySales = sales.filter((sale) => sale.createdAt >= startOfToday);
  const todayTotal = todaySales.reduce((total, sale) => total + sale.total, 0);
  const todayCash = todaySales.filter((sale) => sale.paymentMethod === "CASH").reduce((total, sale) => total + sale.total, 0);
  const todayTransfer = todaySales.filter((sale) => sale.paymentMethod === "BANK_TRANSFER").reduce((total, sale) => total + sale.total, 0);
  const operationVariants = inventory.flatMap((product) => product.variants.map((variant) => ({ ...variant, product: { name: product.name } })));

  return (
    <main className="min-h-screen bg-[var(--paper)]">
      <header className="border-b border-[var(--line)] px-5 py-6 lg:px-10"><div className="mx-auto flex max-w-[1440px] flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><Link href="/" className="display-font text-4xl tracking-[-0.06em]">NOVA<span className="text-[var(--coral)]">.</span></Link><div className="flex flex-wrap items-center gap-x-5 gap-y-3 text-xs font-bold uppercase tracking-[0.1em]"><span>Panel de gestión</span><Link href="/admin/reservas" className="text-[var(--coral)]">Reservas</Link><Link href="/admin/inventario">Inventario</Link><Link href="/admin/movimientos">Movimientos</Link><Link href="/admin/ventas">Ventas</Link><Link href="/admin/compras">Compras</Link><Link href="/" className="text-[var(--coral)]">Volver a tienda</Link></div></div></header>
      <div className="mx-auto max-w-[1440px] px-5 py-10 lg:px-10"><div className="mb-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--coral)]">Operación</p><h1 className="display-font mt-2 text-7xl leading-none tracking-[-0.06em]">Vista general.</h1></div>
        <div className="mb-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><div className="border border-[var(--line)] bg-[#d9e7da] p-6"><p className="text-xs uppercase tracking-[0.12em]">Productos</p><strong className="display-font mt-4 block text-5xl">{products}</strong></div><div className="border border-[var(--line)] bg-[var(--lime)] p-6"><p className="text-xs uppercase tracking-[0.12em]">Reservas pendientes</p><strong className="display-font mt-4 block text-5xl">{pendingOrders}</strong></div><div className="border border-[var(--line)] bg-[var(--coral)] p-6"><p className="text-xs uppercase tracking-[0.12em]">Stock bajo</p><strong className="display-font mt-4 block text-5xl">{lowStockVariants}</strong></div><div className="border border-[var(--line)] bg-white p-6"><p className="text-xs uppercase tracking-[0.12em]">Caja de hoy</p><strong className="display-font mt-4 block text-4xl">{money(todayTotal)}</strong><p className="mt-2 text-xs text-[var(--muted)]">{todaySales.length} ventas</p></div><div className="border border-[var(--line)] bg-white p-6"><p className="text-xs uppercase tracking-[0.12em]">Medios de pago</p><p className="mt-4 text-sm font-bold">Efectivo {money(todayCash)}</p><p className="mt-2 text-sm font-bold">Transferencia {money(todayTransfer)}</p></div></div>
        <Operations variants={operationVariants} />
        <ProductForm />
        <div className="mb-12 border-y border-[var(--line)] py-6"><Link href="/admin/reservas" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-[var(--coral)]">Gestionar todas las reservas <span aria-hidden="true">→</span></Link></div>
        <nav className="mb-12 flex flex-wrap gap-4 border-b border-[var(--line)] pb-6 text-xs font-bold uppercase tracking-[0.1em]"><Link href="/admin/inventario">Inventario</Link><Link href="/admin/movimientos">Movimientos</Link><Link href="/admin/ventas">Ventas</Link><Link href="/admin/compras">Compras</Link></nav>
        <section className="mb-12"><div className="mb-5 border-b border-[var(--line)] pb-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--coral)]">Variantes</p><h2 className="display-font mt-1 text-5xl">Talles y SKU.</h2></div><div className="space-y-6">{inventory.map((product) => <div key={product.id} className="border border-[var(--line)] p-4"><p className="font-bold">{product.name}</p>{product.variants.map((variant) => <div key={variant.id} className="mt-3 flex items-center justify-between gap-3 border-t border-[var(--line)] pt-3"><div><p className="text-sm font-bold">Talle {variant.size}</p><p className="text-xs text-[var(--muted)]">SKU {variant.sku} · {variant.color ?? product.color ?? "Color general"} · Stock {variant.stock}</p></div><VariantEditor variant={{ ...variant, product: { name: product.name } }} /></div>)}<VariantForm productId={product.id} /></div>)}</div></section>
        <section className="mb-12"><div className="mb-5 border-b border-[var(--line)] pb-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--coral)]">Catálogo</p><h2 className="display-font mt-1 text-5xl">Productos publicados.</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{inventory.map((product) => <div key={product.id} className="flex items-center justify-between gap-4 border border-[var(--line)] p-4"><div><p className="font-bold">{product.name}</p><p className="mt-1 text-xs text-[var(--muted)]">{product.active ? "Visible en tienda" : "Oculto de la tienda"}</p></div><ProductStatus productId={product.id} initialActive={product.active} /></div>)}</div></section>
        <section className="mb-12"><div className="mb-5 border-b border-[var(--line)] pb-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--coral)]">Edición</p><h2 className="display-font mt-1 text-5xl">Ajustar catálogo.</h2></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{inventory.map((product) => <div key={`edit-${product.id}`} className="flex items-center justify-between gap-3 border border-[var(--line)] p-4"><div><p className="font-bold">{product.name}</p><p className="text-xs text-[var(--muted)]">{product.category} · {money(product.price)}</p></div><ProductEditor product={product} /></div>)}</div></section>
        <section className="mb-12"><div className="mb-5 border-b border-[var(--line)] pb-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--coral)]">Inventario</p><h2 className="display-font mt-1 text-5xl">Stock por talle</h2></div><div className="overflow-x-auto border border-[var(--line)]"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[var(--ink)] text-xs uppercase tracking-[0.1em] text-[var(--paper)]"><tr><th className="px-4 py-3">Producto</th><th className="px-4 py-3">Categoría</th><th className="px-4 py-3">Talle</th><th className="px-4 py-3">SKU</th><th className="px-4 py-3">Stock</th><th className="px-4 py-3">Modalidad</th></tr></thead><tbody>{inventory.flatMap((product) => product.variants.map((variant) => <tr key={variant.id} className="border-t border-[var(--line)]"><td className="px-4 py-3 font-bold">{product.name}</td><td className="px-4 py-3 text-[var(--muted)]">{product.category}</td><td className="px-4 py-3">{variant.size}</td><td className="px-4 py-3 text-xs text-[var(--muted)]">{variant.sku}</td><td className={`px-4 py-3 font-bold ${variant.stock <= 2 ? "text-[var(--coral)]" : ""}`}>{variant.stock}</td><td className="px-4 py-3 text-xs uppercase">{product.availability === "PREORDER" ? `Encargo · ${product.leadTimeDays} días` : "Inmediato"}</td></tr>))}</tbody></table></div></section>
        <section className="mb-12"><div className="mb-5 border-b border-[var(--line)] pb-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--coral)]">Actividad</p><h2 className="display-font mt-1 text-5xl">Últimas reservas</h2></div><div className="space-y-3">{orders.length === 0 ? <p className="text-sm text-[var(--muted)]">Todavía no hay reservas.</p> : orders.map((order) => <article key={order.id} className="flex flex-col justify-between gap-3 border-b border-[var(--line)] py-4 sm:flex-row sm:items-center"><div><p className="font-bold">#{order.id.slice(-8)} · {order.user.name ?? order.user.email}</p><p className="mt-1 text-xs text-[var(--muted)]">{order.items.map((item) => `${item.productName} x${item.quantity}`).join(" · ")}</p></div><div className="flex items-center gap-5"><OrderStatus orderId={order.id} initialStatus={order.status} /><strong>{money(order.total)}</strong></div></article>)}</div></section>
        <section><div className="mb-5 border-b border-[var(--line)] pb-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--coral)]">Auditoría</p><h2 className="display-font mt-1 text-5xl">Movimientos recientes</h2></div><div className="space-y-2">{movements.length === 0 ? <p className="text-sm text-[var(--muted)]">Todavía no hay movimientos.</p> : movements.map((movement) => <div key={movement.id} className="flex flex-col justify-between gap-2 border-b border-[var(--line)] py-3 text-sm sm:flex-row"><span className="font-bold">{movement.variant.product.name} / talle {movement.variant.size}</span><span className={movement.type === "PURCHASE" ? "text-green-700" : "text-[var(--coral)]"}>{movement.type === "PURCHASE" ? "+" : "-"}{movement.quantity} · {movement.type === "PURCHASE" ? "Entrada" : "Venta presencial"}</span><span className="text-xs text-[var(--muted)]">{movement.note ?? "Sin nota"}</span></div>)}</div></section>
        <section className="mt-12"><div className="mb-5 border-b border-[var(--line)] pb-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--coral)]">Caja</p><h2 className="display-font mt-1 text-5xl">Ventas presenciales.</h2></div><div className="space-y-3">{sales.length === 0 ? <p className="text-sm text-[var(--muted)]">Todavía no hay ventas presenciales.</p> : sales.map((sale) => <article key={sale.id} className="flex flex-col justify-between gap-2 border-b border-[var(--line)] py-4 sm:flex-row sm:items-center"><div><p className="font-bold">Venta #{sale.id.slice(-8)}</p><p className="text-xs text-[var(--muted)]">{sale.items.map((item) => `${item.productName} x${item.quantity}`).join(" · ")}</p></div><div className="flex gap-5 text-xs uppercase tracking-[0.08em]"><span>{sale.paymentMethod === "CASH" ? "Efectivo" : "Transferencia"}</span><strong>{money(sale.total)}</strong></div></article>)}</div></section>
        <section className="mt-12"><div className="mb-5 border-b border-[var(--line)] pb-3"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--coral)]">Compras</p><h2 className="display-font mt-1 text-5xl">Entradas de mercadería.</h2></div><div className="space-y-3">{purchases.length === 0 ? <p className="text-sm text-[var(--muted)]">Todavía no hay compras registradas.</p> : purchases.map((purchase) => <article key={purchase.id} className="flex flex-col justify-between gap-2 border-b border-[var(--line)] py-4 sm:flex-row sm:items-center"><div><p className="font-bold">Compra #{purchase.id.slice(-8)} · {purchase.supplier ?? "Sin proveedor"}</p><p className="text-xs text-[var(--muted)]">{purchase.items.map((item) => `${item.productName} x${item.quantity}`).join(" · ")}</p></div><strong>{purchase.total ? money(purchase.total) : "Costo no informado"}</strong></article>)}</div></section>
      </div>
    </main>
  );
}
